services:
  firefox:
    build: .
    ports:
      - 55800:5800
      - 55900:5900
    environment:
      - ENABLE_CJK_FONT=1
      - LANG=zh_CN.UTF-8
    deploy:
      resources:
        limits:
          cpus: '2.5'
          memory: 4Gib
          # pids: 1
        reservations:
          cpus: '0.5'
          memory: 100M
      replicas: ${FIREFOX_REPLICAS:-1}

      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

    volumes:
      - "firefox_data:/config:rw"
      - "./fcitx/config:/config/fcitx/config"
volumes:
  firefox_data:
